version: "3.9"
services:
  calibreserver:
    build: .
    image: tobias-calibre
    environment:
      - PUID=1000 
      - PGID=1000 
    ports:
      - 8080:8080
    volumes:
      - /data/local/calibre:/library
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

